---
name: Rector + PHP CS Fixer

permissions:
  contents: read

on:
  pull_request_target:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rector-cs.yml'
      - 'composer.json'
      - 'rector.php'
      - '.php-cs-fixer.dist.php'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector-cs.yml@master
    secrets:
      token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      php: '8.1'
